-- ==============================================================================
-- Meme Community - Seed 10 Latest Internet Viral Memes as Learning Modules
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)
-- ==============================================================================

INSERT INTO public.videos (
    id, title, description, category, level, duration, module_code, status, views, thumbnail_url, video_url, instructor_name, instructor_subscribers, instructor_avatar, curriculum, created_at
) VALUES
(
    'vid-11',
    'Chill Guy: The Psychology of Unbothered Stoicism in Youth Culture',
    'Explore why the ''Chill Guy'' cartoon became a defining viral mantra. Analyzes the cultural pivot from hyper-performative hustle culture to unbothered emotional resilience and modern stoicism.',
    'Memes',
    'Beginner',
    '11:20',
    'Module 5.1',
    'published',
    '58.2k',
    'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=kYJydzP-x_0',
    'Dr. Memeology',
    '1.2M Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCsOB1PHfFe7Ii08nY5KY258LkIJpo5gcfO7WaPYR9NEpQVNFJmdgFVBMtgCxljCyw3X08ktMVsMT9DUkBGv6kse-zg1d1OG0EgVE0OjkKqX8YeHcSIQ295cnK0-JBfAH6BgSPlTTNE1uVaXywZ-BFPBbLi7D29kR-_8aapRHQvBewmr__qJrs2qWmMNLNi6JVXQAFEISJyhHFw2V-L_29MYJ8Xl_KTxCywaToBQPI6NWdGZRJIQlbpvw',
    '["Origins: Phil Banks illustration and viral TikTok audio adoption", "Socio-Emotional Analysis: Why students resonate with unbothered personas", "Classroom Discussion: Stoicism vs healthy emotional expression"]'::jsonb,
    '2024-04-01 00:00:00+00'
),
(
    'vid-12',
    'Brat Summer & Chaotic Authenticity: Deconstructing the Anti-Perfection Trend',
    'How the Brat aesthetic shifted digital marketing and visual design. We dissect why lime-green minimalism and raw, imperfect authenticity conquered algorithmic feeds.',
    'Culture',
    'Intermediate',
    '14:40',
    'Module 5.2',
    'published',
    '64.7k',
    'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=ysz5S6PUM-U',
    'Prof. Lingua',
    '840K Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCsOB1PHfFe7Ii08nY5KY258LkIJpo5gcfO7WaPYR9NEpQVNFJmdgFVBMtgCxljCyw3X08ktMVsMT9DUkBGv6kse-zg1d1OG0EgVE0OjkKqX8YeHcSIQ295cnK0-JBfAH6BgSPlTTNE1uVaXywZ-BFPBbLi7D29kR-_8aapRHQvBewmr__qJrs2qWmMNLNi6JVXQAFEISJyhHFw2V-L_29MYJ8Xl_KTxCywaToBQPI6NWdGZRJIQlbpvw',
    '["Color Psychology: Why low-contrast lime green broke visual clutter", "The death of curated millennial aesthetics in favor of Gen Z raw media", "Case Study: Political campaigns and global brands adopting Brat typography"]'::jsonb,
    '2024-04-05 00:00:00+00'
),
(
    'vid-13',
    'The Anatomy of Brainrot: Dadaism, Absurdism, and Short-Form Lore',
    'From ''Skibidi'' and ''Fanum Tax'' to ''Totr'', analyze how the 5-second attention loop gave birth to modern internet Dadaism. Features sociolinguistic and cognitive retention research.',
    'Slang',
    'Advanced',
    '16:15',
    'Module 5.3',
    'published',
    '82.0k',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    'Dr. Sophia Vance',
    '620K Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDQG5761Gj_1MBYEKsKmG6v1l_xubjpj9-wE-L_U49q7dJp68cPrsiRYMTcguMQzVazkkZ3QTvf3_IL4xj7S4P28uti0ZlZ5FbKzLIGVQiDzEq_91prMzWLNu1LsluA4mtcFAf3xMoM7VVqIfT1bYEXSv89DnIcgjUdvkogngcj1SohZyr9VZqUxibTMxaAljSxN_AoXHG6BTL3K7dvupXfRiZvBaINxwz5fLz5_lyLvyjE5W98E3IYKw',
    '["The 1920 Dadaist Art Movement vs 2020s Absurdist Micro-Videos", "Semantic Bleaching: How slang words lose literal meaning and gain social tone", "Teacher Guidance: Addressing Brainrot jargon in student writing"]'::jsonb,
    '2024-04-08 00:00:00+00'
),
(
    'vid-14',
    'Aura Farming & Points: Gamification of Social Capital',
    'Breaking down the ''+10,000 Aura / -5,000 Aura'' sensation. How digital gaming metrics migrated into everyday adolescent social hierarchies and conversational banter.',
    'Culture',
    'Beginner',
    '09:35',
    'Module 6.1',
    'published',
    '49.5k',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=Pi5r0fEZoS8',
    'Tech & Culture Lab',
    '950K Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCJnTEL7t8O_0vf0JSgEv4BnefcIoBxRj6srJ5dq71TVWwvNVmn94lh2dvrc64-W18HWQSI19OmhkaTCkn-dUVERt2u8lJqakIGuLqUQ41VZzzfzMCR5s9eS98NVLITrXngEuU1k4XFJlFSB9u965hFpw_FMejbEDD4Cd8YLSCiXNZNymA7j2exZxOPIptjBvbF7FRZsYX7Hw6sMW_NGSWpdt0tZfLRsj7_MJJUFIoXmmosfgKUtYZYAw',
    '["Game mechanics in real-life: How RPG stats influenced social status", "The humor of losing Aura: Self-deprecating comedy and humility", "Positive classroom reinforcement through mock Aura points"]'::jsonb,
    '2024-04-12 00:00:00+00'
),
(
    'vid-15',
    'The ''6-7'' Phenomenon: Phatic Communication in Digital Slang',
    'Why did an arbitrary number pair become Word of the Year? We explore Phatic Linguistic Theory—words whose primary function is establishing emotional connection rather than conveying literal facts.',
    'Slang',
    'Advanced',
    '12:50',
    'Module 6.2',
    'published',
    '37.8k',
    'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=Uq_vnEMM1xA',
    'Prof. Lingua',
    '840K Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCsOB1PHfFe7Ii08nY5KY258LkIJpo5gcfO7WaPYR9NEpQVNFJmdgFVBMtgCxljCyw3X08ktMVsMT9DUkBGv6kse-zg1d1OG0EgVE0OjkKqX8YeHcSIQ295cnK0-JBfAH6BgSPlTTNE1uVaXywZ-BFPBbLi7D29kR-_8aapRHQvBewmr__qJrs2qWmMNLNi6JVXQAFEISJyhHFw2V-L_29MYJ8Xl_KTxCywaToBQPI6NWdGZRJIQlbpvw',
    '["Linguistic theory: Phatic tokens vs Lexical definitions", "TikTok algorithm soundbite feedback mechanics", "Understanding student in-jokes without feeling excluded"]'::jsonb,
    '2024-04-15 00:00:00+00'
),
(
    'vid-16',
    'Lookalike Competitions: When Digital Memes Become Real-Life Gatherings',
    'From the Timothée Chalamet lookalike contest in Washington Square Park to global imitator meetups, examine how irony-fueled online memes are reversing digital isolation by driving offline community events.',
    'Culture',
    'Intermediate',
    '13:10',
    'Module 6.3',
    'published',
    '45.3k',
    'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=qk3rjG-dc_k',
    'History Buffs',
    '890K Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDQG5761Gj_1MBYEKsKmG6v1l_xubjpj9-wE-L_U49q7dJp68cPrsiRYMTcguMQzVazkkZ3QTvf3_IL4xj7S4P28uti0ZlZ5FbKzLIGVQiDzEq_91prMzWLNu1LsluA4mtcFAf3xMoM7VVqIfT1bYEXSv89DnIcgjUdvkogngcj1SohZyr9VZqUxibTMxaAljSxN_AoXHG6BTL3K7dvupXfRiZvBaINxwz5fLz5_lyLvyjE5W98E3IYKw',
    '["The Flash Mob 2.0: How algorithmic coordination drives IRL gatherings", "Costume satire, public performance art, and spontaneous community", "Engaging students in participatory public projects"]'::jsonb,
    '2024-04-18 00:00:00+00'
),
(
    'vid-17',
    'The Costco Guys: Family Influencing & Retail Absurdism',
    'How a father-son duo turning warehouse bulk shopping into catchphrase theatre (''Five Big Booms!'') redefined wholesome algorithmic virality and retail consumerist satire.',
    'Memes',
    'Beginner',
    '08:45',
    'Module 7.1',
    'published',
    '51.9k',
    'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=ZO53RSN2OqM',
    'Dr. Memeology',
    '1.2M Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCsOB1PHfFe7Ii08nY5KY258LkIJpo5gcfO7WaPYR9NEpQVNFJmdgFVBMtgCxljCyw3X08ktMVsMT9DUkBGv6kse-zg1d1OG0EgVE0OjkKqX8YeHcSIQ295cnK0-JBfAH6BgSPlTTNE1uVaXywZ-BFPBbLi7D29kR-_8aapRHQvBewmr__qJrs2qWmMNLNi6JVXQAFEISJyhHFw2V-L_29MYJ8Xl_KTxCywaToBQPI6NWdGZRJIQlbpvw',
    '["The Wholesome Anti-Hero: Why hyper-earnest content cuts through cynicism", "Catchphrase mechanics and acoustic repetition on TikTok", "Using food and retail memes to teach economics and consumer marketing"]'::jsonb,
    '2024-04-20 00:00:00+00'
),
(
    'vid-18',
    'Jet2Holiday Subversions: Audio Juxtaposition & Disaster Comedy',
    'Dissecting the trend of taking cheerful vacation commercial jingles and pairing them with chaotic life failures. Explores dramatic irony and audiovisual cognitive dissonance.',
    'Memes',
    'Intermediate',
    '10:15',
    'Module 7.2',
    'published',
    '33.4k',
    'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=nuvLxgYfsoo',
    'StemMemes Lab',
    '1.1M Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBelj7BrJI8cTV1RQfXWPDdnAfP4lGYfs5Y0kks60GBMNLhCdyCyaWnsE-f6GA8s9hLezKiU6um7NNQWzn7nBj_WXH28wBMIlZYIVLFKKfIoj7IVYO_zyM4MbTKhxRW7spnNUtd3p8aNA1FtKJVwioNIFBSb_ykel-mDi0PNhp9CgdBMCl8HARsYV-bABqHnXwtjtVMle3mjkGP8EEUSYFCdYtLbfJzxIKxcJ2x-NxVKAZDjOig6HD7OA',
    '["Cognitive dissonance: Happy audio layered over unfortunate situations", "Irony as an emotional coping mechanism for modern challenges", "Sound design and media editing pedagogy"]'::jsonb,
    '2024-04-22 00:00:00+00'
),
(
    'vid-19',
    'Labubu & Ugly-Cute Aesthetics: The Psychology of Modern Status Symbols',
    'Why did a toothy plush monster explode into a luxury collectible status symbol? We investigate the ''Kimo-Kawaii'' (ugly-cute) psychological attraction and FOMO influencer economics.',
    'Culture',
    'Intermediate',
    '12:00',
    'Module 7.3',
    'published',
    '56.8k',
    'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=lSJP5z5S8T4',
    'Dr. Sophia Vance',
    '620K Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDQG5761Gj_1MBYEKsKmG6v1l_xubjpj9-wE-L_U49q7dJp68cPrsiRYMTcguMQzVazkkZ3QTvf3_IL4xj7S4P28uti0ZlZ5FbKzLIGVQiDzEq_91prMzWLNu1LsluA4mtcFAf3xMoM7VVqIfT1bYEXSv89DnIcgjUdvkogngcj1SohZyr9VZqUxibTMxaAljSxN_AoXHG6BTL3K7dvupXfRiZvBaINxwz5fLz5_lyLvyjE5W98E3IYKw',
    '["K-Pop cross-pollination: Lisa (BLACKPINK) and organic celebrity virality", "The Ugly-Cute psychology: Flawed character design and emotional attachment", "Artificial scarcity, blind box consumerism, and youth trends"]'::jsonb,
    '2024-04-25 00:00:00+00'
),
(
    'vid-20',
    'FOOH & Synthetic Media: Dissecting Fake-Out-Of-Home & AI Hyper-Realism',
    'Giant 3D digital objects walking down city streets: how CGI and Generative AI marketing tricks users into double-taking, and how media literacy protects students from synthetic misinformation.',
    'Technology',
    'Advanced',
    '15:30',
    'Module 8.1',
    'published',
    '68.0k',
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    'https://www.youtube.com/watch?v=v2cUJ3gkuEg',
    'Tech & Culture Lab',
    '950K Scholars',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCJnTEL7t8O_0vf0JSgEv4BnefcIoBxRj6srJ5dq71TVWwvNVmn94lh2dvrc64-W18HWQSI19OmhkaTCkn-dUVERt2u8lJqakIGuLqUQ41VZzzfzMCR5s9eS98NVLITrXngEuU1k4XFJlFSB9u965hFpw_FMejbEDD4Cd8YLSCiXNZNymA7j2exZxOPIptjBvbF7FRZsYX7Hw6sMW_NGSWpdt0tZfLRsj7_MJJUFIoXmmosfgKUtYZYAw',
    '["Defining FOOH: Blurring the boundary between real geography and CGI", "Critical Media Literacy: 5 signs a viral video spectacle is synthetic", "Teaching deepfake awareness and digital evidence evaluation"]'::jsonb,
    '2024-04-28 00:00:00+00'
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    level = EXCLUDED.level,
    duration = EXCLUDED.duration,
    module_code = EXCLUDED.module_code,
    thumbnail_url = EXCLUDED.thumbnail_url,
    video_url = EXCLUDED.video_url,
    curriculum = EXCLUDED.curriculum;
