import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#6d28d9",
        "on-primary": "#ffffff",
        "primary-container": "#eaddff",
        "on-primary-container": "#24005a",
        secondary: "#625b71",
        "on-secondary": "#ffffff",
        "secondary-container": "#e8def8",
        "on-secondary-container": "#1d192b",
        tertiary: "#7d5260",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffd8e4",
        "on-tertiary-container": "#31111d",
        error: "#b3261e",
        "on-error": "#ffffff",
        "error-container": "#f9dedc",
        "on-error-container": "#410e0b",
        background: "#faf8ff",
        "on-background": "#1d1b20",
        surface: "#ffffff",
        "on-surface": "#1d1b20",
        "surface-variant": "#e7e0ec",
        "on-surface-variant": "#49454f",
        outline: "#79747e",
        "outline-variant": "#cac4d0",
        shadow: "#000000",
        scrim: "#000000",
        "inverse-surface": "#322f35",
        "inverse-on-surface": "#f5eff7",
        "inverse-primary": "#d0bcff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eceeff",
        "surface-container-high": "#e6e8ff",
        "surface-container-highest": "#e0e3ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        gutter: "20px",
        xl: "40px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        md: "16px",
        xs: "4px",
        unit: "4px",
        lg: "24px",
        sm: "8px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-sm": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      keyframes: {
        float1: {
          "0%, 100%": { transform: "translateY(0) rotate(-2deg)" },
          "50%": { transform: "translateY(-20px) rotate(1deg)" },
        },
        float2: {
          "0%, 100%": { transform: "translateY(0) rotate(3deg) scale(0.9)" },
          "50%": { transform: "translateY(-15px) rotate(-1deg) scale(0.95)" },
        },
        float3: {
          "0%, 100%": { transform: "translateY(0) rotate(-1deg) scale(1.1)" },
          "50%": { transform: "translateY(-25px) rotate(2deg) scale(1.05)" },
        },
        pulseGlow: {
          "0%": { boxShadow: "0 0 0 0 rgba(109, 40, 217, 0.4)" },
          "70%": { boxShadow: "0 0 0 10px rgba(109, 40, 217, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(109, 40, 217, 0)" },
        },
      },
      animation: {
        float1: "float1 6s ease-in-out infinite",
        float2: "float2 8s ease-in-out infinite 1s",
        float3: "float3 7s ease-in-out infinite 2s",
        pulseGlow: "pulseGlow 2s infinite",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
