"use client";

import React, { useState, useEffect } from "react";
import { INITIAL_MEME_TRENDS, MemeTrend } from "@/lib/data/mock-data";
import SuggestMemeModal from "@/components/tracker/SuggestMemeModal";
import MemeDetailModal from "@/components/tracker/MemeDetailModal";
import { Sparkles, ArrowRight, TrendingUp, Layers, RefreshCw, Lock, LogIn, UserPlus } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import Link from "next/link";

export default function MemeTrackerPage() {
  const { user } = useAuth();
  const [trends, setTrends] = useState<MemeTrend[]>(INITIAL_MEME_TRENDS);
  const [selectedMeme, setSelectedMeme] = useState<MemeTrend | null>(null);
  const [isSuggestModalOpen, setIsSuggestModalOpen] = useState<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const fetchTrends = async () => {
    setIsLoading(true);
    try {
      const res = await fetch(`/api/memes?_t=${Date.now()}`, {
        cache: "no-store",
        headers: { "Cache-Control": "no-cache, no-store, must-revalidate" },
      });
      const data = await res.json();
      if (data.data && Array.isArray(data.data)) {
        setTrends(data.data);
      }
    } catch (e) {
      console.warn("Meme tracker fetch error:", e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchTrends();
  }, []);

  return (
    <div className="w-full flex flex-col min-h-screen relative pb-28 lg:pb-12">
      {/* Locking Overlay if not logged in */}
      {!user && (
        <div className="absolute inset-0 z-30 bg-background/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-surface-container-lowest border border-outline-variant rounded-3xl p-6 md:p-8 max-w-md w-full text-center shadow-2xl space-y-4 animate-fadeIn inner-glow">
            <div className="w-14 h-14 rounded-2xl bg-primary-container text-primary flex items-center justify-center mx-auto shadow-sm">
              <Lock className="w-7 h-7" />
            </div>
            <h3 className="font-headline-md text-xl md:text-2xl font-extrabold text-on-surface">
              Unlock Meme Radar
            </h3>
            <p className="text-xs md:text-sm text-on-surface-variant leading-relaxed">
              Sign in or register to analyze trending internet slang, access origin dossiers, and use the OpenAI Slang Explainer.
            </p>
            <div className="flex flex-col sm:flex-row gap-2 pt-2 justify-center">
              <Link
                href="/auth"
                className="bg-primary hover:bg-primary/90 text-on-primary font-bold text-xs py-2.5 px-5 rounded-xl flex items-center justify-center gap-1.5 shadow-sm active:scale-95 transition-all"
              >
                <LogIn className="w-4 h-4" />
                Sign In
              </Link>
              <Link
                href="/auth"
                className="bg-surface-container border border-outline-variant hover:border-primary text-on-surface font-bold text-xs py-2.5 px-5 rounded-xl flex items-center justify-center gap-1.5 transition-all"
              >
                <UserPlus className="w-4 h-4" />
                Create Free Account
              </Link>
            </div>
          </div>
        </div>
      )}

      <div className={`w-full flex flex-col ${!user ? "filter blur-[2px] pointer-events-none select-none" : ""}`}>
        {/* Hero Section */}
        <section className="w-full hero-gradient pt-12 pb-10 px-4 md:px-12 relative overflow-hidden flex flex-col items-center text-center justify-center min-h-[300px] border-b border-outline-variant/60">
          <div className="max-w-3xl relative z-10 flex flex-col items-center gap-4">
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-primary-container/80 border border-primary/30 text-on-primary-container text-xs font-bold">
              <Sparkles className="w-3.5 h-3.5 text-primary" />
              Real-Time Meme & Slang Radar
            </div>

            <h2 className="font-display-lg text-3xl md:text-5xl lg:text-[56px] font-extrabold text-on-surface tracking-tight leading-tight">
              Stay Ahead of Every{" "}
              <span className="text-primary drop-shadow-[0_0_15px_rgba(109,40,217,0.25)]">
                Trend
              </span>
            </h2>

            <p className="font-body-lg text-sm md:text-base text-on-surface-variant max-w-xl mx-auto leading-relaxed">
              Track, analyze, and understand the cultural impact of internet phenomena in real-time. Intellectually electric meme analysis generated by OpenAI.
            </p>

            <div className="flex items-center gap-3 mt-2">
              <button
                onClick={() => setIsSuggestModalOpen(true)}
                className="bg-primary hover:bg-primary/90 text-on-primary font-label-md text-xs md:text-sm py-3 px-6 rounded-xl hover:shadow-[0_0_16px_rgba(109,40,217,0.35)] transition-all flex items-center justify-center gap-2 font-bold shadow-md active:scale-95 group"
              >
                <Sparkles className="w-4 h-4 group-hover:rotate-12 transition-transform" />
                Suggest & Explain a Meme
              </button>
              <button
                onClick={fetchTrends}
                title="Refresh Tracker"
                className="p-3 text-on-surface-variant hover:text-primary rounded-xl bg-surface-container border border-outline-variant hover:bg-surface-variant transition-colors"
              >
                <RefreshCw className={`w-4 h-4 ${isLoading ? "animate-spin" : ""}`} />
              </button>
            </div>
          </div>

          <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-primary/8 rounded-full blur-[100px] pointer-events-none"></div>
          <div className="absolute bottom-0 right-1/4 w-[400px] h-[400px] bg-secondary-container/40 rounded-full blur-[80px] pointer-events-none"></div>
        </section>

        {/* Content Grid */}
        <section className="max-w-[1280px] w-full mx-auto px-4 md:px-8 py-8">
          <div className="flex justify-between items-center mb-6">
            <h3 className="font-headline-md text-xl font-bold text-on-surface flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-primary" />
              Active Cultural Radar ({trends.length})
            </h3>
            <span className="text-xs text-on-surface-variant font-medium">
              Updated via OpenAI & Community
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {trends.map((trend) => (
              <article
                key={trend.id}
                onClick={() => setSelectedMeme(trend)}
                className="bg-surface-container-lowest border border-outline-variant rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-all flex flex-col h-full group cursor-pointer card-lift"
              >
                <div className="relative w-full aspect-video bg-surface-container overflow-hidden">
                  <img
                    src={trend.image_url}
                    alt={trend.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute top-3 right-3 bg-surface/85 border border-outline-variant px-2.5 py-1 rounded-full flex items-center gap-1.5 backdrop-blur-md shadow-xs">
                    <Sparkles className="w-3.5 h-3.5 text-primary" />
                    <span className="font-label-sm text-[11px] font-bold text-primary">
                      AI Explained
                    </span>
                  </div>
                  <div className="absolute bottom-3 left-3 bg-black/70 backdrop-blur-md px-2.5 py-0.5 rounded-full text-[10px] font-bold text-white">
                    {trend.category}
                  </div>
                </div>

                <div className="p-5 flex flex-col flex-1 gap-3 justify-between">
                  <div>
                    <h4 className="font-headline-md text-lg font-bold text-on-surface group-hover:text-primary transition-colors">
                      {trend.title}
                    </h4>
                    <p className="font-body-md text-xs text-on-surface-variant line-clamp-3 leading-relaxed mt-1">
                      {trend.description}
                    </p>
                  </div>

                  <div className="mt-auto pt-3 flex justify-between items-center border-t border-outline-variant/60">
                    <span className="font-label-sm text-xs font-semibold text-outline">
                      Status: <strong className="text-on-surface">{trend.trend_status}</strong>
                    </span>
                    <button className="text-on-surface group-hover:text-primary transition-colors p-1.5 rounded-lg group-hover:bg-primary/10">
                      <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </button>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </section>

        {/* Suggest Meme Modal */}
        {isSuggestModalOpen && (
          <SuggestMemeModal
            isOpen={isSuggestModalOpen}
            onClose={() => setIsSuggestModalOpen(false)}
            onMemeAnalyzed={() => {
              fetchTrends();
            }}
          />
        )}

        {/* Meme Detail Modal */}
        {selectedMeme && (
          <MemeDetailModal
            meme={selectedMeme}
            onClose={() => setSelectedMeme(null)}
          />
        )}
      </div>
    </div>
  );
}
